/**
 * npm run contract:export
 * Builds a throwaway database from the migrations and writes the ownership contract and the state machines from the
 * tables that ENFORCE them (field_contract, state_machine_states, state_transitions), so the docs cannot drift:
 *   docs/source-of-truth.json   machine-readable contract (every Airtable field + canonical-only facts)
 *   docs/source-of-truth.md     the same, as tables per entity
 *   docs/state-machines.md      Mermaid diagram + transition table per machine
 */
import { writeFileSync } from 'node:fs';
import { openPglite } from '../src/db/db.js';
import { migrate } from '../src/db/migrate.js';

const db = await openPglite();
await migrate(db);
type Row = Record<string, string | boolean | null>;
const contract = await db.query<Row>(`select entity, field_key, airtable_table_id, airtable_field_id, airtable_name, canonical, owner, editable_in,
  change_path, validation, event_generated, downstream, readback, reconcile, ai_visible from field_contract order by entity, (owner <> 'AIRTABLE_EDIT'), field_key`);
const states = await db.query<Row>(`select machine, state, label, is_terminal from state_machine_states order by machine, state`);
const trans = await db.query<Row>(`select machine, from_state, to_state, guard, note from state_transitions order by machine, from_state, to_state`);
await db.close();

const OWNER: Record<string, string> = {
  POSTGRES: 'RoofOps (Postgres)', AIRTABLE_EDIT: 'RoofOps (Postgres); staff may change it in Airtable via the validated handler',
  INPUT: 'Airtable input read with another change (not stored as its own truth)', ACTION: 'Airtable action button (command, not state)',
  WORKFLOW: 'Written by a RoofOps workflow (projection)', DRIVE: 'Google Drive object, verified link in Postgres', XERO: 'Xero object, verified link in Postgres',
};
const RECON: Record<string, string> = {
  APPLY_VIA_HANDLER: 'missed edit replayed through the same validation', REPAIR_AIRTABLE: 'Airtable put back to RoofOps value',
  PROJECTION: 'Airtable projection refreshed when canonical state is stable', VERIFY_EXTERNAL: 'external object read back (Drive / Xero)', IGNORE: 'not compared',
};

writeFileSync('docs/source-of-truth.json', JSON.stringify({
  generated_from: 'supabase/migrations (table field_contract)', owners: OWNER, reconcile_strategies: RECON, fields: contract,
}, null, 2) + '\n');

const md: string[] = ['# Source-of-truth contract', '',
  'Generated by `npm run contract:export` from the `field_contract` table, which **drives** Airtable change capture (`wf_airtable_change`) and',
  'reconciliation (`wf_reconcile_airtable`). Editing this file changes nothing; change the migration.', '',
  '**Rule:** Postgres is canonical for every business fact. Airtable is an editing surface for the fields marked *editable*; everything else in',
  'Airtable is a projection RoofOps writes and repairs. Google Drive and Xero hold the objects; Postgres holds the verified link to them.', '',
  '| Owner code | Meaning |', '|---|---|', ...Object.entries(OWNER).map(([k, v]) => `| \`${k}\` | ${v} |`), '',
  '| Reconcile code | What reconciliation does on drift |', '|---|---|', ...Object.entries(RECON).map(([k, v]) => `| \`${k}\` | ${v} |`), ''];
for (const entity of [...new Set(contract.map((c) => String(c.entity)))]) {
  md.push(`## ${entity}`, '', '| Field | Canonical | Owner | Editable where | Change path | Validation | Event | Downstream | Read-back | Reconcile | AI |',
    '|---|---|---|---|---|---|---|---|---|---|---|');
  for (const c of contract.filter((x) => x.entity === entity)) {
    const cell = (v: string | boolean | null | undefined) => String(v ?? '—').replace(/\|/g, '\\|');
    md.push(`| ${cell(c.airtable_name ?? c.field_key)}${c.airtable_field_id ? `<br>\`${String(c.airtable_field_id)}\`` : ''} | ${cell(c.canonical)} | \`${String(c.owner)}\` | ${cell(c.editable_in)} | ${cell(c.change_path)} | ${cell(c.validation)} | ${cell(c.event_generated)} | ${cell(c.downstream)} | ${cell(c.readback)} | \`${String(c.reconcile)}\` | ${c.ai_visible ? 'yes' : 'no'} |`);
  }
  md.push('');
}
writeFileSync('docs/source-of-truth.md', md.join('\n'));

const sm: string[] = ['# State machines', '',
  'Generated by `npm run contract:export` from `state_machine_states` / `state_transitions`. These rows are the single definition: the',
  '`enforce_state_machine()` trigger refuses any other status change on the real tables (even from SQL that bypasses the application),',
  '`project_transition_guard()` adds the business guards, and `test/state-integrity.test.ts` generates every (from, to) pair from them.', ''];
for (const machine of [...new Set(states.map((s) => String(s.machine)))]) {
  const st = states.filter((s) => s.machine === machine);
  const tr = trans.filter((t) => t.machine === machine);
  sm.push(`## ${machine}`, '', '```mermaid', 'stateDiagram-v2');
  for (const s of st) sm.push(`  ${String(s.state)}: ${String(s.label)}`);
  for (const t of tr) sm.push(`  ${String(t.from_state)} --> ${String(t.to_state)}${t.guard ? `: ${String(t.guard)}` : ''}`);
  for (const s of st.filter((x) => x.is_terminal)) sm.push(`  ${String(s.state)} --> [*]`);
  sm.push('```', '', `Terminal: ${st.filter((s) => s.is_terminal).map((s) => String(s.state)).join(', ') || 'none'}. `
    + `Every pair not listed below is refused (${st.length * (st.length - 1) - tr.length} of ${st.length * (st.length - 1)} possible changes).`, '',
    '| From | To | Guard | Note |', '|---|---|---|---|', ...tr.map((t) => `| ${String(t.from_state)} | ${String(t.to_state)} | ${String(t.guard ?? '—')} | ${String(t.note ?? '—')} |`), '');
}
writeFileSync('docs/state-machines.md', sm.join('\n'));
console.log(`contract: ${contract.length} fields; ${new Set(states.map((s) => s.machine)).size} machines, ${trans.length} legal transitions`);
